# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "265234d25e033a025833cefeef932871"
application_url = "https://trackbacks-seeing-stud-losses.trycloudflare.com"
embedded = true
name = "4PH Platform API"
handle = "4ph-platform-api"

[build]
automatically_update_urls_on_dev = false
dev_store_url = "moka-it-solutions.myshopify.com"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[auth]
redirect_urls = [
  "https://trackbacks-seeing-stud-losses.trycloudflare.com/auth/callback",
  "https://trackbacks-seeing-stud-losses.trycloudflare.com/auth/shopify/callback",
  "https://trackbacks-seeing-stud-losses.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
